---
- hosts: "{{ hosts }}"
  become: true

  tasks:
    - name: Create unit file
      template:
        src: systemd-unit.j2
        dest: /etc/systemd/system/docker-{{ container_name }}.service
        owner: root
        group: root
        mode: 0644
      register: create_unit_file
    
    - name: Create env directory
      file:
        path: /etc/container_envs
        state: directory
    

    - name: Create env file
      template:
        src: "{{ container_name }}.env.j2"
        dest: /etc/container_envs/{{ container_name }}.env
        owner: root
        group: root
        mode: 0644
      register: create_env_file
